name: TKDL CI/CD Pipeline

on:
  push:
    branches: [ "main" ]   # Runs on push to main branch
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java (if Spring Boot)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build project with Maven
      - name: Build Project
        run: mvn clean package -DskipTests

      # Step 4: Log in to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build Docker image
      - name: Build Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/tkdl-app
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:${{ github.sha }}
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/tkdl-app
            docker pull ${{ secrets.DOCKER_USERNAME }}/tkdl-app:latest
            docker stop tkdl-app || true
            docker rm tkdl-app || true
            docker run -d --name tkdl-app -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/tkdl-app:latest
