name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Build with Maven
      - name: Build Project
        run: mvn clean package -DskipTests

      # 4. Verify target directory
      - name: Verify Target Folder
        run: |
          echo "Checking JAR/WAR build output..."
          ls -lh target || echo "Target folder missing!"

      # 5. Save built JAR/WAR as an artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tkdl-artifact
          path: target/*.jar
